STRINGS.NAMES.CHANGCHUNMAO = "niu hat"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.CHANGCHUNMAO = "cool hat"
STRINGS.RECIPE_DESC.CHANGCHUNMAO= "level up hat"

STRINGS.NAMES.WINDYKNIFE = "Breeze Dagger"
STRINGS.RECIPE_DESC.WINDYKNIFE = "A nice dagger are easy to use"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.WINDYKNIFE = "It's too exquisite for me to believe"