STRINGS.TOTOORIAST = {
}

STRINGS.TOTOORIATAB = "托托莉的知识库"

STRINGS.NAMES.TOTOORIASTAFF1 = "托托莉的法杖Lv1"
STRINGS.RECIPE_DESC.TOTOORIASTAFF1 = "cosplay经常会用到的破棍"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TOTOORIASTAFF1 = "感觉就像拿着一根塑料棍"

STRINGS.NAMES.TOTOORIASTAFF2 = "托托莉的法杖Lv2"
STRINGS.RECIPE_DESC.TOTOORIASTAFF2 = "集斧头矿锄锤子铲子于一身"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TOTOORIASTAFF2 = "再也不用带一身的工具了"

STRINGS.NAMES.TOTOORIASTAFF3 = "托托莉的法杖Lv3"
STRINGS.RECIPE_DESC.TOTOORIASTAFF3 = "远程攻击，会冻住，能灭火"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TOTOORIASTAFF3 = "冻不住自己，冻不住时间......"

STRINGS.NAMES.TOTOORIASTAFF4 = "托托莉的法杖Lv4"
STRINGS.RECIPE_DESC.TOTOORIASTAFF4 = "还能和步行手杖一样的加速"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TOTOORIASTAFF4 = "值得一年四季都拿在手上"

STRINGS.NAMES.TOTOORIASTAFF5GREEN = "托托莉的绿法杖"
STRINGS.RECIPE_DESC.TOTOORIASTAFF5GREEN = "根据幸运有不同概率复制一个物品"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TOTOORIASTAFF5GREEN = "很贵的，要小心用才行"

STRINGS.NAMES.TOTOORIASTAFF5ORANGE = "托托莉的橙法杖"
STRINGS.RECIPE_DESC.TOTOORIASTAFF5ORANGE = "瞬移"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TOTOORIASTAFF5ORANGE = "拿起来就感觉身体变轻了"

STRINGS.NAMES.TOTOORIASTAFF5YELLOW = "托托莉的黄法杖"
STRINGS.RECIPE_DESC.TOTOORIASTAFF5YELLOW = "永久的光照，不需要装备上"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TOTOORIASTAFF5YELLOW = "会发光的法杖才叫法杖。就差不能变大了......"

STRINGS.NAMES.TBOOK_BIRDS = STRINGS.NAMES.BOOK_BIRDS
STRINGS.RECIPE_DESC.TBOOK_BIRDS = STRINGS.RECIPE_DESC.BOOK_BIRDS
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TBOOK_BIRDS = STRINGS.CHARACTERS.GENERIC.DESCRIBE.BOOK_BIRDS

STRINGS.NAMES.TBOOK_GARDENING = STRINGS.NAMES.BOOK_GARDENING
STRINGS.RECIPE_DESC.TBOOK_GARDENING = STRINGS.RECIPE_DESC.BOOK_GARDENING
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TBOOK_GARDENING = STRINGS.CHARACTERS.GENERIC.DESCRIBE.BOOK_GARDENING

STRINGS.NAMES.TBOOK_SLEEP = STRINGS.NAMES.BOOK_SLEEP
STRINGS.RECIPE_DESC.TBOOK_SLEEP = STRINGS.RECIPE_DESC.BOOK_SLEEP
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TBOOK_SLEEP = STRINGS.CHARACTERS.GENERIC.DESCRIBE.BOOK_SLEEP

STRINGS.NAMES.TBOOK_BRIMSTONE = STRINGS.NAMES.BOOK_BRIMSTONE
STRINGS.RECIPE_DESC.TBOOK_BRIMSTONE = STRINGS.RECIPE_DESC.BOOK_BRIMSTONE
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TBOOK_BRIMSTONE = STRINGS.CHARACTERS.GENERIC.DESCRIBE.BOOK_BRIMSTONE

STRINGS.NAMES.TBOOK_TENTACLES = STRINGS.NAMES.BOOK_TENTACLES
STRINGS.RECIPE_DESC.TBOOK_TENTACLES = STRINGS.RECIPE_DESC.BOOK_TENTACLES
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TBOOK_TENTACLES = STRINGS.CHARACTERS.GENERIC.DESCRIBE.BOOK_TENTACLES

STRINGS.NAMES.TBOOK_HORTICULTURE = STRINGS.NAMES.BOOK_HORTICULTURE
STRINGS.RECIPE_DESC.TBOOK_HORTICULTURE = STRINGS.RECIPE_DESC.BOOK_HORTICULTURE
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TBOOK_HORTICULTURE = STRINGS.CHARACTERS.GENERIC.DESCRIBE.BOOK_HORTICULTURE

STRINGS.NAMES.TBOOK_SILVICULTURE = STRINGS.NAMES.BOOK_SILVICULTURE
STRINGS.RECIPE_DESC.TBOOK_SILVICULTURE = STRINGS.RECIPE_DESC.BOOK_SILVICULTURE
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TBOOK_SILVICULTURE = STRINGS.CHARACTERS.GENERIC.DESCRIBE.BOOK_SILVICULTURE

STRINGS.NAMES.TOTOORIAGLASSES = "专家眼镜"
STRINGS.RECIPE_DESC.TOTOORIAGLASSES = "双倍经验值获取量"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TOTOORIAGLASSES = "保持集中，学得更快"

STRINGS.NAMES.PHILOSOPHERSTONE = "贤者之石"
STRINGS.RECIPE_DESC.PHILOSOPHERSTONE = "炼金术知识的结晶"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.PHILOSOPHERSTONE = "太棒了！我可以躺家里混吃混喝了。"

STRINGS.NAMES.TOTOORIAHAT = "波奈特装饰帽"
STRINGS.RECIPE_DESC.TOTOORIAHAT = "隔绝雨露，保持头发干净"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TOTOORIAHAT = "很重，但是发型不能乱！"

STRINGS.NAMES.TPORTABLESPICER_ITEM = STRINGS.NAMES.PORTABLESPICER_ITEM
STRINGS.RECIPE_DESC.TPORTABLESPICER_ITEM = STRINGS.RECIPE_DESC.PORTABLESPICER_ITEM
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TPORTABLESPICER_ITEM = STRINGS.CHARACTERS.GENERIC.DESCRIBE.PORTABLESPICER_ITEM

STRINGS.NAMES.TPORTABLEBLENDER_ITEM = STRINGS.NAMES.PORTABLEBLENDER_ITEM
STRINGS.RECIPE_DESC.TPORTABLEBLENDER_ITEM = STRINGS.RECIPE_DESC.PORTABLEBLENDER_ITEM
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TPORTABLEBLENDER_ITEM = STRINGS.CHARACTERS.GENERIC.DESCRIBE.PORTABLEBLENDER_ITEM

STRINGS.NAMES.TTRSOUNDPREFAB = "复制"

STRINGS.RECIPE_DESC.GOLDNUGGET = "制造1个金块"
STRINGS.RECIPE_DESC.ROCKS = "制造4个岩石"
STRINGS.RECIPE_DESC.FLINT = "制造3个燧石"
STRINGS.RECIPE_DESC.NITRE = "制造3个硝石"
STRINGS.RECIPE_DESC.SPOILED_FOOD = "制造4个长满毛毛的腐烂食物"
STRINGS.RECIPE_DESC.LIGHTBULB = "制造4个好吃的荧光果"
STRINGS.RECIPE_DESC.ICE = "透心凉，心飞扬"
STRINGS.RECIPE_DESC.STEELWOOL = "如果你实在翻不出，就合成吧"
STRINGS.RECIPE_DESC.LIVINGLOG = "活着的木头就叫活木"
STRINGS.RECIPE_DESC.LUREPLANTBULB = "免费提供Lv"
STRINGS.RECIPE_DESC.MANDRAKE = "它的根有特殊的功用"
STRINGS.RECIPE_DESC.GEARS = "这些会让它们动起来的"
STRINGS.RECIPE_DESC.REDGEM = "闪着炽热的光"
STRINGS.RECIPE_DESC.BLUEGEM = "闪着冰冷的光"
STRINGS.RECIPE_DESC.GREENGEM = "涂点果汁，让我们炸开它"
STRINGS.RECIPE_DESC.ORANGEGEM = "涂点果汁，艺术就是爆炸"
STRINGS.RECIPE_DESC.YELLOWGEM = "让我们炸开它然后再炸开它"
STRINGS.RECIPE_DESC.THULECITE_PIECES = "制造3个碎片"
STRINGS.RECIPE_DESC.SALTROCK = "生物制盐"

STRINGS.CHARACTER_TITLES.totooria = "托托莉.赫尔蒙德"
STRINGS.CHARACTER_NAMES.totooria = "totooria"
STRINGS.CHARACTER_DESCRIPTIONS.totooria = "*喜欢读书\n*拥有特别的生存技能\n*自带可升级的法杖"
STRINGS.CHARACTER_QUOTES.totooria = "不知道自己在寻找着什么"

STRINGS.CHARACTERS.GENERIC.DESCRIBE.totooria = 
{
	GENERIC = "这是谁!",
	ATTACKER = "打啊",
	MURDERER = "谋杀啊!",
	REVIVER = "啥玩意儿?!",
	GHOST = "我是鬼",
}

STRINGS.NAMES.totooria = "totooria"

STRINGS.TTRSTRINGS={
[1] = "等级提升啦!",
[2] = "获得特技[友善]",
[3] = "获得特技[大厨]",
[4] = "获得特技[巧手]",
[5] = "获得特技[学者]",
[6] = "现在有 ",
[7] = " 个技能点",
[8] = "按 K 查看加点方向",
[9] = "等级太低了，不能重置技能点",
[10] = "技能点重置了!",
[11] = "失去特技[巧手]",
[12] = "失去特技[大厨]",
[13] = "失去特技[友善]",
[14] = "失去特技[学者]",
[15] = "现在是 Lv",
[16] = " 有 ",
[17] = "等级 ",
[18] = "Lv",
[19] = "幸运加成 ",
[20] = "%",
[21] = "当前伤害 ",
[22] = "移速加成 ",
[23] = "血量加成 ",
[24] = "幸运提升了 10%",
[25] = "按 J 查看加点明细",
[26] = "没有技能点了",
[27] = "移速提升了 2.5%",
[28] = "攻击力提升了 3.75%",
[29] = "血量提升了 8%",
[30] = "按上键增加幸运 10.0%",
[31] = "按左键增加攻击 3.75%",
[32] = "按下键增加移速 2.50%",
[33] = "按右键增加血量 6.25",
[34] = "技能点 ",
[35] = "那不能复制!",
[36] = "获得特技[勇敢]",
[37] = "获得特技[嗜血]",
[38] = "获得特技[灵巧]",
[39] = "啊啊啊啊啊!",
[40] = "飞起来啦!",
[41] = "跑啊啊啊!",
[42] = "快跑!!",
[43] = "我快不行了…",
[44] = "结束了",
[45] = "以下重要的事情说五遍",
[46] = "我更新了，被洗点了一下",
[47] = "但对等级和已获得的特技没有影响",
[48] = "请重新加点",
[49] = "exp ",
[50] = "能量足够了!",
[51] = "还不够能量",
[52] = "易如反掌",
[53] = "Power+ ",
}

STRINGS.TTRUI={
[1] = "托托莉玩法说明",
[2] = "托托莉加点说明",
[3] = "托托莉特技说明",
[4] = "【嗜血】",
[5] = "【勇敢】",
[6] = "【灵巧】",
[7] = "【友善】",
[8] = "【大厨】",
[9] = "【巧手】",
[10] = "【学者】",
[11] = "别点了，我知道你很想点",
[12] = "但是现在还不能点",
[13] = "【友善】已开启",
[14] = "【大厨】已开启",
[15] = "【巧手】已开启",
[16] = "【学者】已开启",
[17] = "【友善】已关闭",
[18] = "【大厨】已关闭",
[19] = "【巧手】已关闭",
[20] = "【学者】已关闭",
[21] = "再次点击可开启",
[22] = "再次点击可关闭",
[23] = "我需要到达 ",
[24] = " 以上才能获得这个特技",
}