STRINGS.TOTOORIAST = {
}

STRINGS.TOTOORIATAB = "Totooria's knowledge"

STRINGS.NAMES.TOTOORIASTAFF1 = "TotooriaStaffLv1"
STRINGS.RECIPE_DESC.TOTOORIASTAFF1 = "You often use it for cosplay"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TOTOORIASTAFF1 = "It feels like plastic"

STRINGS.NAMES.TOTOORIASTAFF2 = "TotooriaStaffLv2"
STRINGS.RECIPE_DESC.TOTOORIASTAFF2 = "As axes, pickaxes, hammers and shovels"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TOTOORIASTAFF2 = "I have no need to carry that many tools in my backpack anymore"

STRINGS.NAMES.TOTOORIASTAFF3 = "TotooriaStaffLv3"
STRINGS.RECIPE_DESC.TOTOORIASTAFF3 = "Ranged Attack, can freeze and extinguish"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TOTOORIASTAFF3 = "It can't freeze me, and it can't freeze time......"

STRINGS.NAMES.TOTOORIASTAFF4 = "TotooriaStaffLv4"
STRINGS.RECIPE_DESC.TOTOORIASTAFF4 = "It speeds me up like a cane does"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TOTOORIASTAFF4 = "So useful that I shall hold onto it at all times"

STRINGS.NAMES.TOTOORIASTAFF5GREEN = "TotooriaStaffgreen"
STRINGS.RECIPE_DESC.TOTOORIASTAFF5GREEN = "Increased chance to duplicate an item"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TOTOORIASTAFF5GREEN = "It's expensive, so use it sparingly"

STRINGS.NAMES.TOTOORIASTAFF5ORANGE = "TotooriaStafforange"
STRINGS.RECIPE_DESC.TOTOORIASTAFF5ORANGE = "Teleport"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TOTOORIASTAFF5ORANGE = "I feel light when I equip it"

STRINGS.NAMES.TOTOORIASTAFF5YELLOW = "TotooriaStaffyellow"
STRINGS.RECIPE_DESC.TOTOORIASTAFF5YELLOW = "Bright forever, no need to equip"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TOTOORIASTAFF5YELLOW = "But it can't make me bigger......"

STRINGS.NAMES.TBOOK_BIRDS = STRINGS.NAMES.BOOK_BIRDS
STRINGS.RECIPE_DESC.TBOOK_BIRDS = STRINGS.RECIPE_DESC.BOOK_BIRDS
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TBOOK_BIRDS = STRINGS.CHARACTERS.GENERIC.DESCRIBE.BOOK_BIRDS

STRINGS.NAMES.TBOOK_GARDENING = STRINGS.NAMES.BOOK_GARDENING
STRINGS.RECIPE_DESC.TBOOK_GARDENING = STRINGS.RECIPE_DESC.BOOK_GARDENING
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TBOOK_GARDENING = STRINGS.CHARACTERS.GENERIC.DESCRIBE.BOOK_GARDENING

STRINGS.NAMES.TBOOK_SLEEP = STRINGS.NAMES.BOOK_SLEEP
STRINGS.RECIPE_DESC.TBOOK_SLEEP = STRINGS.RECIPE_DESC.BOOK_SLEEP
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TBOOK_SLEEP = STRINGS.CHARACTERS.GENERIC.DESCRIBE.BOOK_SLEEP

STRINGS.NAMES.TBOOK_BRIMSTONE = STRINGS.NAMES.BOOK_BRIMSTONE
STRINGS.RECIPE_DESC.TBOOK_BRIMSTONE = STRINGS.RECIPE_DESC.BOOK_BRIMSTONE
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TBOOK_BRIMSTONE = STRINGS.CHARACTERS.GENERIC.DESCRIBE.BOOK_BRIMSTONE

STRINGS.NAMES.TBOOK_TENTACLES = STRINGS.NAMES.BOOK_TENTACLES
STRINGS.RECIPE_DESC.TBOOK_TENTACLES = STRINGS.RECIPE_DESC.BOOK_TENTACLES
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TBOOK_TENTACLES = STRINGS.CHARACTERS.GENERIC.DESCRIBE.BOOK_TENTACLES

STRINGS.NAMES.TBOOK_HORTICULTURE = STRINGS.NAMES.BOOK_HORTICULTURE
STRINGS.RECIPE_DESC.TBOOK_HORTICULTURE = STRINGS.RECIPE_DESC.BOOK_HORTICULTURE
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TBOOK_HORTICULTURE = STRINGS.CHARACTERS.GENERIC.DESCRIBE.BOOK_HORTICULTURE

STRINGS.NAMES.TBOOK_SILVICULTURE = STRINGS.NAMES.BOOK_SILVICULTURE
STRINGS.RECIPE_DESC.TBOOK_SILVICULTURE = STRINGS.RECIPE_DESC.BOOK_SILVICULTURE
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TBOOK_SILVICULTURE = STRINGS.CHARACTERS.GENERIC.DESCRIBE.BOOK_SILVICULTURE

STRINGS.NAMES.TOTOORIAGLASSES = "Expert Glasses"
STRINGS.RECIPE_DESC.TOTOORIAGLASSES = "Double the experience earned."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TOTOORIAGLASSES = "Concentrate and I shall learn better."

STRINGS.NAMES.PHILOSOPHERSTONE = "Philosopher Stone"
STRINGS.RECIPE_DESC.PHILOSOPHERSTONE = "The crystal of the alchemy's knowledge."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.PHILOSOPHERSTONE = "Wonderful! Now I gonna to stay at home and wait to feed."

STRINGS.NAMES.TOTOORIAHAT = "Bonnet Hat"
STRINGS.RECIPE_DESC.TOTOORIAHAT = "Keep away from rain and keep your hair clean"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TOTOORIAHAT = "It's heavy, but don't let your hair get messy!"

STRINGS.NAMES.TPORTABLESPICER_ITEM = STRINGS.NAMES.PORTABLESPICER_ITEM
STRINGS.RECIPE_DESC.TPORTABLESPICER_ITEM = STRINGS.RECIPE_DESC.PORTABLESPICER_ITEM
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TPORTABLESPICER_ITEM = STRINGS.CHARACTERS.GENERIC.DESCRIBE.PORTABLESPICER_ITEM

STRINGS.NAMES.TPORTABLEBLENDER_ITEM = STRINGS.NAMES.PORTABLEBLENDER_ITEM
STRINGS.RECIPE_DESC.TPORTABLEBLENDER_ITEM = STRINGS.RECIPE_DESC.PORTABLEBLENDER_ITEM
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TPORTABLEBLENDER_ITEM = STRINGS.CHARACTERS.GENERIC.DESCRIBE.PORTABLEBLENDER_ITEM

STRINGS.NAMES.TTRSOUNDPREFAB = "Duplicate"

STRINGS.RECIPE_DESC.GOLDNUGGET = "Make 1 Goldnugget."
STRINGS.RECIPE_DESC.ROCKS = "Make 4 Rocks."
STRINGS.RECIPE_DESC.FLINT = "Make 3 Flints."
STRINGS.RECIPE_DESC.NITRE = "Make 3 Nitres."
STRINGS.RECIPE_DESC.SPOILED_FOOD = "Make 4 Rots."
STRINGS.RECIPE_DESC.LIGHTBULB = "Make 4 Lightbulbs."
STRINGS.RECIPE_DESC.ICE = STRINGS.CHARACTERS.GENERIC.DESCRIBE.ICE
STRINGS.RECIPE_DESC.STEELWOOL = STRINGS.CHARACTERS.GENERIC.DESCRIBE.STEELWOOL
STRINGS.RECIPE_DESC.LIVINGLOG = STRINGS.CHARACTERS.GENERIC.DESCRIBE.LIVINGLOG
STRINGS.RECIPE_DESC.LUREPLANTBULB = STRINGS.CHARACTERS.GENERIC.DESCRIBE.LUREPLANTBULB
STRINGS.RECIPE_DESC.MANDRAKE = STRINGS.CHARACTERS.GENERIC.DESCRIBE.MANDRAKE
STRINGS.RECIPE_DESC.GEARS = STRINGS.CHARACTERS.GENERIC.DESCRIBE.GEARS
STRINGS.RECIPE_DESC.REDGEM = STRINGS.CHARACTERS.GENERIC.DESCRIBE.REDGEM
STRINGS.RECIPE_DESC.BLUEGEM = STRINGS.CHARACTERS.GENERIC.DESCRIBE.BLUEGEM
STRINGS.RECIPE_DESC.GREENGEM = STRINGS.CHARACTERS.GENERIC.DESCRIBE.GREENGEM
STRINGS.RECIPE_DESC.ORANGEGEM = STRINGS.CHARACTERS.GENERIC.DESCRIBE.ORANGEGEM
STRINGS.RECIPE_DESC.YELLOWGEM = STRINGS.CHARACTERS.GENERIC.DESCRIBE.YELLOWGEM
STRINGS.RECIPE_DESC.THULECITE_PIECES = "Make 3 Thulecite Pieces."
STRINGS.RECIPE_DESC.SALTROCK = "Biological salt making."

STRINGS.CHARACTER_TITLES.totooria = "Totooria Helmold"
STRINGS.CHARACTER_NAMES.totooria = "Totooria"
STRINGS.CHARACTER_DESCRIPTIONS.totooria = "*Favor in reading\n*Special skills\n*Has a staff"
STRINGS.CHARACTER_QUOTES.totooria = "I don't know what I'm searching for..."

STRINGS.CHARACTERS.GENERIC.DESCRIBE.totooria = 
{
	GENERIC = "Who's this!",
	ATTACKER = "Fight!",
	MURDERER = "Murder!",
	REVIVER = "What?",
	GHOST = "I'm a ghost",
}

STRINGS.NAMES.totooria = "Totooria"

STRINGS.TTRSTRINGS={
[1] = "levelUP!",
[2] = "getskill [Friendliness]",
[3] = "getskill [Chef]",
[4] = "getskill [Ingenious]",
[5] = "getskill [Expert]",
[6] = "Now I have ",
[7] = " PT",
[8] = "press K to check upgrade",
[9] = "Level too low, can't reset PT",
[10] = "PT reset!",
[11] = "loseskill [Ingenious]",
[12] = "loseskill [Chef]",
[13] = "loseskill [Friendly]",
[14] = "loseskill [Expert]",
[15] = "Lv",
[16] = " I have ",
[17] = "I'm ",
[18] = "Lv",
[19] = "Luck ",
[20] = "%",
[21] = "Damage ",
[22] = "Speed ",
[23] = "Health ",
[24] = "Luck + 10%",
[25] = "Press J to check PT details",
[26] = "I have no PT",
[27] = "Speed + 2.5%",
[28] = "Damage + 3.75%",
[29] = "Health + 8%",
[30] = "Press Up for Luck+10.0%",
[31] = "Press Left for Damage+3.75%",
[32] = "Press Down for Speed+2.50%",
[33] = "Press Right for Health+6.25",
[34] = "PT:",
[35] = "I can't copy that!",
[36] = "getskill [Bravery]",
[37] = "getskill [Vampirism]",
[38] = "getskill [Agility]",
[39] = "Ahhhhhhhhh!",
[40] = "I believe I can fly!",
[41] = "Go Go Go!",
[42] = "Run!!",
[43] = "I'm almost die...",
[44] = "It's over.",
[45] = "I need to repeat the important things 5 times",
[46] = "I've been upgraded with skill point reset",
[47] = "But it does not affect my level or acquired special skills",
[48] = "Please reassign my skill points",
[49] = "exp ",
[50] = "Energy enough!",
[51] = "Not enough energy",
[52] = "Pretty Easy",
[53] = "Power+ ",
}

STRINGS.TTRUI={
[1] = "Totooria's user guide",
[2] = "Totooria's skill point guide",
[3] = "Totooria's special skills guide",
[4] = "[Vampirism]",
[5] = "[Bravery]",
[6] = "[Agility]",
[7] = "[Friendliness]",
[8] = "[Chef]",
[9] = "[Ingenious]",
[10] = "[Expert]",
[11] = "Stop trying to add points, I already know you want to",
[12] = "But now it isn't time",
[13] = "[Friendliness]On",
[14] = "[Chef]On",
[15] = "[Ingenious]On",
[16] = "[Expert]On",
[17] = "[Friendliness]Off",
[18] = "[Chef]Off",
[19] = "[Ingenious]Off",
[20] = "[Expert]Off",
[21] = "Press again to turn On",
[22] = "Press again to turn Off",
[23] = "I need to reach ",
[24] = " in order to learn this skill",
}