STRINGS.CARNEYTAB = "制造"

STRINGS.NAMES.BOOK_HARVEST = "收获的时刻" -- 物体在游戏中显示的名字
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BOOK_HARVEST = "小猫又想偷懒了" -- 物体的检查描述
STRINGS.RECIPE_DESC.BOOK_HARVEST = "丰收的喜悦" -- 物体的制作栏描述

--护符
STRINGS.NAMES.LINGDONGAMULET = "护身符"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.LINGDONGAMULET = "最好的礼物祝福你"
STRINGS.RECIPE_DESC.LINGDONGAMULET= "心爱的护身符"

--铠甲
STRINGS.NAMES.KJ = "内衬软甲"         
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KJ= "一定要保护好自己呀"  
STRINGS.RECIPE_DESC.KJ = "相当强悍的软甲" 

STRINGS.NAMES.WHITEBERET = "白色贝雷帽"
STRINGS.RECIPE_DESC.WHITEBERET = "出门不能忘记戴帽子"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.WHITEBERET = "涤纶的质感，不像是手工纺织品"

STRINGS.NAMES.ANGELCRYSTAL = "天使水晶"
STRINGS.RECIPE_DESC.ANGELCRYSTAL = "蕴含影响心智的能量"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.ANGELCRYSTAL = "一下子开窍了"

STRINGS.NAMES.WINDYKNIFE = "微风短剑"
STRINGS.RECIPE_DESC.WINDYKNIFE = "顺手的短剑怎么用都顺手"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.WINDYKNIFE = "精巧得难以置信"

STRINGS.NAMES.NYLON = "尼龙背包"
STRINGS.RECIPE_DESC.NYLON = "加强了压缩带的防水型内框架背包"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.NYLON = "很大却很轻，非常厚实"

STRINGS.CHARACTER_TITLES.carney = "卡尼猫"
STRINGS.CHARACTER_NAMES.carney = "Carney"
STRINGS.CHARACTER_DESCRIPTIONS.carney = "*灵活的战斗技能\n*随着时间逐渐成长\n*喜欢一直在旅行"
STRINGS.CHARACTER_QUOTES.carney = "正在到处旅行着"

STRINGS.CHARACTERS.GENERIC.DESCRIBE.carney = 
{
	GENERIC = "你这瓜保熟吗？",
	ATTACKER = "打哭你丫的",
	MURDERER = "救命啊，萨日朗!",
	REVIVER = "what's up?什么乖乖!",
	GHOST = "凉凉月色为我思念成河",
}

STRINGS.NAMES.carney = "Carney"

STRINGS.CARNEYSTRINGS={
[1] = "等级提升啦!",
}

STRINGS.CARNEYUI={
[1] = "玩法说明",
}