--护符
STRINGS.NAMES.LINGDONGAMULET = "护身符"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.LINGDONGAMULET = "最好的礼物祝福你"
STRINGS.RECIPE_DESC.LINGDONGAMULET= "心爱的护身符"

--铠甲
STRINGS.NAMES.KJ = "内衬软甲"         
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KJ= "一定要保护好自己呀"  
STRINGS.RECIPE_DESC.KJ = "相当强悍的软甲" 